---
title: "Example tasks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example tasks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

This article gives a brief description of how some example tasks might be completed with the fantasy package.

## Analysing the best value for money
Possible
- Read in and visualise player info with `get_players()`
- See each players individual contributions this season with `get_fixture_stats()`
- Look at upcoming fixtures with `get_fixture_list()`
- Investigate individual season progression with `get_player_summary()`

## Automating injury-avoidance
- Schedule R script to run that checks your team for injuries:
- Read in team with `get_my_team()`
- Use `get_players()` to identify injured players (status column)
- Check which of your squad aren't expected to start with `get_predicted_lineups()`
- Identify possible replacements with `get_transfer_targets()` and set conditions for using wildcard/free-hit with `activate_chip()`
- Confirm the changes with `update_team()`
