#' @import dplyr
#' @importFrom stats setNames
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL

global_vars <- c("at_home",
                 "cost",
                 "cost_change_event",
                 "cost_change_start",
                 "deadline",
                 "difficulty",
                 "element",
                 "element_id",
                 "entry_name",
                 "ep_next",
                 "ep_this",
                 "event",
                 "event_points",
                 "event_total",
                 "finished",
                 "first_name",
                 "fixture",
                 "fixture_id",
                 "form",
                 "gameweek",
                 "is_captain",
                 "is_home",
                 "is_vice_captain",
                 "kickoff_time",
                 "known_as",
                 "league_type",
                 "minutes",
                 "name",
                 "now_cost",
                 "opponent_team",
                 "penalties_order",
                 "player",
                 "player_name",
                 "points",
                 "points_per_game",
                 "points_total",
                 "position",
                 "second_name",
                 "selected_by_pct",
                 "selected_by_percent",
                 "selection",
                 "status",
                 "team_a",
                 "team_a_difficulty",
                 "team_a_score",
                 "team_code",
                 "team_h",
                 "team_h_difficulty",
                 "team_h_score",
                 "team_id",
                 "total",
                 "total_points",
                 "transfers_in",
                 "transfers_in_event",
                 "transfers_out",
                 "transfers_out_event",
                 "value",
                 "value_form",
                 "value_season",
                 "was_home",
                 "web_name")
utils::globalVariables(global_vars)
